In [1]:
import pyreadr
import pandas as pd
import numpy as np

In [2]:
fault_free_test = pyreadr.read_r('TEP_FaultFree_Testing.RData')
fault_free_train = pyreadr.read_r('TEP_FaultFree_Training.RData')
faulty_test = pyreadr.read_r('TEP_Faulty_Testing.RData')
faulty_train = pyreadr.read_r('TEP_Faulty_Training.RData')

In [3]:
fault_free_test

OrderedDict([('fault_free_testing',
                      faultNumber  simulationRun  sample  xmeas_1  xmeas_2  xmeas_3  \
              0                 0            1.0       1  0.25171   3672.4   4466.3
              1                 0            1.0       2  0.25234   3642.2   4568.7
              2                 0            1.0       3  0.24840   3643.1   4507.5
              3                 0            1.0       4  0.25153   3628.3   4519.3
              4                 0            1.0       5  0.21763   3655.8   4571.0
              ...             ...            ...     ...      ...      ...      ...
              479995            0          500.0     956  0.26428   3671.5   4510.8
              479996            0          500.0     957  0.25132   3573.4   4483.9
              479997            0          500.0     958  0.25105   3622.6   4433.3
              479998            0          500.0     959  0.24521   3660.5   4485.2
              479999            0          500.0     960  0.24373   3652.1   4471.8

                      xmeas_4  xmeas_5  xmeas_6  xmeas_7  ...   xmv_2   xmv_3   xmv_4  \
              0        9.5122   27.057   42.473   2705.6  ...  54.494  24.527  59.710
              1        9.4145   26.999   42.586   2705.2  ...  53.269  24.465  60.466
              2        9.2901   26.927   42.278   2703.5  ...  54.000  24.860  60.642
              3        9.3347   26.999   42.330   2703.9  ...  53.860  24.553  61.908
              4        9.3087   26.901   42.402   2707.7  ...  53.307  21.775  61.891
              ...         ...      ...      ...      ...  ...     ...     ...     ...
              479995   9.2852   27.141   42.297   2699.9  ...  53.942  26.022  61.709
              479996   9.2872   26.604   42.311   2698.1  ...  53.760  24.585  61.267
              479997   9.3998   26.707   41.936   2699.5  ...  54.366  24.613  61.745
              479998   9.3885   26.936   42.639   2700.5  ...  53.289  24.371  62.811
              479999   9.4359   27.309   42.015   2703.9  ...  53.450  24.516  60.734

                       xmv_5   xmv_6   xmv_7   xmv_8   xmv_9  xmv_10  xmv_11
              0       22.357  40.149  40.074  47.955  47.300  42.100  15.345
              1       22.413  39.956  36.651  45.038  47.502  40.553  16.063
              2       22.199  40.074  41.868  44.553  47.479  41.341  20.452
              3       21.981  40.141  40.066  48.048  47.440  40.780  17.123
              4       22.412  37.696  38.295  44.678  47.530  41.089  18.681
              ...        ...     ...     ...     ...     ...     ...     ...
              479995  22.417  40.510  36.731  50.115  52.721  40.927  18.854
              479996  21.928  39.893  34.136  47.714  52.908  41.412  18.847
              479997  22.212  40.098  35.585  48.241  53.099  40.150  16.791
              479998  22.249  39.536  35.609  46.495  53.157  41.065  17.097
              479999  22.731  39.131  39.078  43.477  53.407  41.596  16.697

              [480000 rows x 55 columns])])

In [4]:
fault_free_train

OrderedDict([('fault_free_training',
                      faultNumber  simulationRun  sample  xmeas_1  xmeas_2  xmeas_3  \
              0               0.0            1.0       1  0.25038   3674.0   4529.0
              1               0.0            1.0       2  0.25109   3659.4   4556.6
              2               0.0            1.0       3  0.25038   3660.3   4477.8
              3               0.0            1.0       4  0.24977   3661.3   4512.1
              4               0.0            1.0       5  0.29405   3679.0   4497.0
              ...             ...            ...     ...      ...      ...      ...
              249995          0.0          500.0     496  0.29325   3640.1   4473.0
              249996          0.0          500.0     497  0.29134   3625.7   4506.2
              249997          0.0          500.0     498  0.29438   3600.2   4478.3
              249998          0.0          500.0     499  0.25269   3683.5   4486.4
              249999          0.0          500.0     500  0.25214   3648.2   4467.8

                      xmeas_4  xmeas_5  xmeas_6  xmeas_7  ...   xmv_2   xmv_3   xmv_4  \
              0        9.2320   26.889   42.402   2704.3  ...  53.744  24.657  62.544
              1        9.4264   26.721   42.576   2705.0  ...  53.414  24.588  59.259
              2        9.4426   26.875   42.070   2706.2  ...  54.357  24.666  61.275
              3        9.4776   26.758   42.063   2707.2  ...  53.946  24.725  59.856
              4        9.3381   26.889   42.650   2705.1  ...  53.658  28.797  60.717
              ...         ...      ...      ...      ...  ...     ...     ...     ...
              249995   9.1949   26.867   42.379   2700.2  ...  53.429  29.249  60.773
              249996   9.2109   26.889   42.291   2700.6  ...  53.830  28.975  61.517
              249997   9.1957   26.820   42.448   2700.3  ...  54.163  28.676  61.656
              249998   9.2832   27.188   42.757   2697.4  ...  53.453  24.889  61.564
              249999   9.1344   26.886   42.534   2695.1  ...  53.676  24.943  61.254

                       xmv_5   xmv_6   xmv_7   xmv_8   xmv_9  xmv_10  xmv_11
              0       22.137  39.935  42.323  47.757  47.510  41.258  18.447
              1       22.084  40.176  38.554  43.692  47.427  41.359  17.194
              2       22.380  40.244  38.990  46.699  47.468  41.199  20.530
              3       22.277  40.257  38.072  47.541  47.658  41.643  18.089
              4       21.947  39.144  41.955  47.645  47.346  41.507  18.461
              ...        ...     ...     ...     ...     ...     ...     ...
              249995  21.532  40.451  34.064  48.953  48.291  40.812  18.756
              249996  21.750  42.762  42.645  51.055  48.589  40.933  19.360
              249997  21.487  42.109  39.770  46.770  48.648  41.465  19.344
              249998  21.392  39.334  42.274  43.623  48.797  39.835  18.512
              249999  21.208  38.991  42.873  44.400  48.876  41.076  16.158

              [250000 rows x 55 columns])])

In [5]:
faulty_test

OrderedDict([('faulty_testing',
                       faultNumber  simulationRun  sample  xmeas_1  xmeas_2  xmeas_3  \
              0                  1            1.0       1  0.25171   3672.4   4466.3
              1                  1            1.0       2  0.25234   3642.2   4568.7
              2                  1            1.0       3  0.24840   3643.1   4507.5
              3                  1            1.0       4  0.25153   3628.3   4519.3
              4                  1            1.0       5  0.21763   3655.8   4571.0
              ...              ...            ...     ...      ...      ...      ...
              9599995           20          500.0     956  0.26494   3719.6   4536.7
              9599996           20          500.0     957  0.25252   3724.0   4494.3
              9599997           20          500.0     958  0.25164   3700.8   4537.3
              9599998           20          500.0     959  0.29097   3641.8   4525.2
              9599999           20          500.0     960  0.29359   3622.2   4485.1

                       xmeas_4  xmeas_5  xmeas_6  xmeas_7  ...   xmv_2   xmv_3   xmv_4  \
              0         9.5122   27.057   42.473   2705.6  ...  54.494  24.527  59.710
              1         9.4145   26.999   42.586   2705.2  ...  53.269  24.465  60.466
              2         9.2901   26.927   42.278   2703.5  ...  54.000  24.860  60.642
              3         9.3347   26.999   42.330   2703.9  ...  53.860  24.553  61.908
              4         9.3087   26.901   42.402   2707.7  ...  53.307  21.775  61.891
              ...          ...      ...      ...      ...  ...     ...     ...     ...
              9599995   9.2265   26.875   42.401   2708.3  ...  54.382  26.018  62.068
              9599996   9.1873   27.221   41.999   2706.0  ...  54.236  25.098  61.557
              9599997   9.2514   26.659   42.180   2704.7  ...  53.722  25.185  61.169
              9599998   9.3053   26.823   42.234   2705.0  ...  54.185  28.771  61.140
              9599999   9.3070   26.922   42.610   2704.8  ...  54.665  28.513  59.399

                        xmv_5   xmv_6   xmv_7   xmv_8   xmv_9  xmv_10  xmv_11
              0        22.357  40.149  40.074  47.955  47.300  42.100  15.345
              1        22.413  39.956  36.651  45.038  47.502  40.553  16.063
              2        22.199  40.074  41.868  44.553  47.479  41.341  20.452
              3        21.981  40.141  40.066  48.048  47.440  40.780  17.123
              4        22.412  37.696  38.295  44.678  47.530  41.089  18.681
              ...         ...     ...     ...     ...     ...     ...     ...
              9599995  20.708  37.589  35.121  45.496  42.653  40.816  15.846
              9599996  20.655  40.934  38.391  43.699  42.832  41.853  18.486
              9599997  20.650  40.694  35.961  45.643  43.147  40.538  18.127
              9599998  20.323  39.774  39.807  45.989  43.318  40.826  17.305
              9599999  20.145  39.467  40.264  42.916  43.557  40.845  20.782

              [9600000 rows x 55 columns])])

In [6]:
faulty_train

OrderedDict([('faulty_training',
                       faultNumber  simulationRun  sample  xmeas_1  xmeas_2  xmeas_3  \
              0                  1            1.0       1  0.25038   3674.0   4529.0
              1                  1            1.0       2  0.25109   3659.4   4556.6
              2                  1            1.0       3  0.25038   3660.3   4477.8
              3                  1            1.0       4  0.24977   3661.3   4512.1
              4                  1            1.0       5  0.29405   3679.0   4497.0
              ...              ...            ...     ...      ...      ...      ...
              4999995           20          500.0     496  0.23419   3655.3   4461.7
              4999996           20          500.0     497  0.26704   3647.4   4540.2
              4999997           20          500.0     498  0.26543   3630.3   4571.6
              4999998           20          500.0     499  0.27671   3655.7   4498.9
              4999999           20          500.0     500  0.27421   3640.4   4474.4

                       xmeas_4  xmeas_5  xmeas_6  xmeas_7  ...   xmv_2   xmv_3   xmv_4  \
              0         9.2320   26.889   42.402   2704.3  ...  53.744  24.657  62.544
              1         9.4264   26.721   42.576   2705.0  ...  53.414  24.588  59.259
              2         9.4426   26.875   42.070   2706.2  ...  54.357  24.666  61.275
              3         9.4776   26.758   42.063   2707.2  ...  53.946  24.725  59.856
              4         9.3381   26.889   42.650   2705.1  ...  53.658  28.797  60.717
              ...          ...      ...      ...      ...  ...     ...     ...     ...
              4999995   9.3448   27.008   42.481   2703.0  ...  53.670  23.350  61.061
              4999996   9.3546   27.034   42.671   2704.7  ...  54.650  26.362  60.020
              4999997   9.4089   27.129   42.470   2705.1  ...  54.274  26.521  59.824
              4999998   9.3781   27.353   42.281   2705.8  ...  53.506  26.781  62.818
              4999999   9.3866   27.145   41.985   2706.0  ...  53.800  27.027  59.757

                        xmv_5   xmv_6   xmv_7   xmv_8   xmv_9  xmv_10  xmv_11
              0        22.137  39.935  42.323  47.757  47.510  41.258  18.447
              1        22.084  40.176  38.554  43.692  47.427  41.359  17.194
              2        22.380  40.244  38.990  46.699  47.468  41.199  20.530
              3        22.277  40.257  38.072  47.541  47.658  41.643  18.089
              4        21.947  39.144  41.955  47.645  47.346  41.507  18.461
              ...         ...     ...     ...     ...     ...     ...     ...
              4999995  20.719  40.999  38.653  47.386  47.528  40.212  17.659
              4999996  20.263  41.579  33.624  47.536  47.647  41.199  18.741
              4999997  20.189  41.505  40.967  52.437  47.802  41.302  23.199
              4999998  20.453  40.208  40.957  47.628  48.086  40.510  15.932
              4999999  20.157  40.326  36.039  48.885  48.170  41.115  15.752

              [5000000 rows x 55 columns])])

In [7]:
fault_free_test['fault_free_testing'].columns

Index(['faultNumber', 'simulationRun', 'sample', 'xmeas_1', 'xmeas_2',
       'xmeas_3', 'xmeas_4', 'xmeas_5', 'xmeas_6', 'xmeas_7', 'xmeas_8',
       'xmeas_9', 'xmeas_10', 'xmeas_11', 'xmeas_12', 'xmeas_13', 'xmeas_14',
       'xmeas_15', 'xmeas_16', 'xmeas_17', 'xmeas_18', 'xmeas_19', 'xmeas_20',
       'xmeas_21', 'xmeas_22', 'xmeas_23', 'xmeas_24', 'xmeas_25', 'xmeas_26',
       'xmeas_27', 'xmeas_28', 'xmeas_29', 'xmeas_30', 'xmeas_31', 'xmeas_32',
       'xmeas_33', 'xmeas_34', 'xmeas_35', 'xmeas_36', 'xmeas_37', 'xmeas_38',
       'xmeas_39', 'xmeas_40', 'xmeas_41', 'xmv_1', 'xmv_2', 'xmv_3', 'xmv_4',
       'xmv_5', 'xmv_6', 'xmv_7', 'xmv_8', 'xmv_9', 'xmv_10', 'xmv_11'],
      dtype='object')

In [8]:
fault_free_test['fault_free_testing'].describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,480000.0,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,...,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000,480000.000000
mean,0.0,250.500000,480.500000,0.250526,3663.764171,4508.898696,9.346866,26.902165,42.337820,2705.013416,...,53.974160,24.643706,61.295689,22.212485,40.057926,38.098705,46.534148,47.975245,41.103468,18.122284
std,0.0,144.337429,277.128268,0.031273,33.943033,39.398350,0.086148,0.211148,0.218114,7.578226,...,0.470525,3.076030,1.246459,0.536269,1.532972,2.966680,2.348197,2.815153,0.542646,1.464914
min,0.0,1.000000,1.000000,0.122610,3503.300000,4338.200000,8.936300,26.018000,41.441000,2667.800000,...,51.818000,11.985000,55.762000,19.847000,32.596000,24.594000,36.354000,35.587000,38.557000,10.856000
25%,0.0,125.750000,240.750000,0.229390,3640.800000,4482.300000,9.288800,26.759000,42.190000,2699.900000,...,53.656000,22.564000,60.449000,21.855000,39.025000,36.078000,44.934000,46.136000,40.738000,17.131000
50%,0.0,250.500000,480.500000,0.250520,3663.800000,4508.900000,9.346900,26.902000,42.338000,2704.900000,...,53.974000,24.646000,61.297000,22.210000,40.059000,38.103000,46.536000,47.858000,41.103000,18.122000
75%,0.0,375.250000,720.250000,0.271600,3686.800000,4535.500000,9.405100,27.045000,42.486000,2710.000000,...,54.292000,26.716000,62.142000,22.568000,41.094000,40.120000,48.137000,49.808000,41.469000,19.113000
max,0.0,500.000000,960.000000,0.390320,3824.700000,4689.200000,9.748900,27.822000,43.250000,2736.900000,...,56.103000,38.449000,66.494000,24.654000,46.758000,50.631000,56.357000,60.160000,43.601000,24.524000

In [9]:
fault_free_train['fault_free_training'].describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,250000.0,250000.000000,250000.000000,250000.000000,250000.000000,250000.00000,250000.000000,250000.000000,250000.000000,250000.000000,...,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,0.0,250.500000,250.500000,0.250482,3663.785706,4508.81979,9.347101,26.902196,42.337598,2705.037865,...,53.973668,24.639472,61.298501,22.216644,40.055456,38.098898,46.534295,47.958591,41.104304,18.118706
std,0.0,144.337567,144.337567,0.030873,34.006357,39.21542,0.085721,0.211485,0.218513,7.525596,...,0.469663,3.037743,1.243805,0.530156,1.526751,2.965266,2.351304,2.716520,0.540817,1.463678
min,0.0,1.000000,1.000000,0.122450,3511.800000,4336.90000,8.972700,25.951000,41.394000,2672.300000,...,52.095000,11.977000,55.961000,19.749000,33.389000,25.959000,36.937000,36.641000,38.586000,11.705000
25%,0.0,125.750000,125.750000,0.229770,3640.800000,4482.40000,9.289300,26.758000,42.188000,2700.100000,...,53.657000,22.602000,60.453000,21.864000,39.021000,36.081000,44.931000,46.265000,40.740000,17.130000
50%,0.0,250.500000,250.500000,0.250510,3663.700000,4508.80000,9.347100,26.902000,42.338000,2705.000000,...,53.974000,24.644000,61.298000,22.217000,40.058000,38.091000,46.530000,47.820000,41.104000,18.119000
75%,0.0,375.250000,375.250000,0.271200,3686.800000,4535.30000,9.405100,27.046000,42.487000,2710.000000,...,54.290000,26.674000,62.144000,22.568000,41.084000,40.117000,48.140000,49.651000,41.470000,19.111000
max,0.0,500.000000,500.000000,0.391740,3808.400000,4683.70000,9.729800,27.818000,43.257000,2739.100000,...,56.118000,38.351000,66.443000,24.525000,47.498000,50.729000,56.443000,59.616000,43.930000,24.762000

In [10]:
faulty_test['faulty_testing'].describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,...,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06,9.600000e+06
mean,1.050000e+01,2.505000e+02,4.805000e+02,2.565512e-01,3.665140e+03,4.510175e+03,9.389582e+00,2.690135e+01,4.237570e+01,2.725131e+03,...,5.473719e+01,2.935285e+01,6.373647e+01,2.328299e+01,3.925227e+01,3.804629e+01,4.642267e+01,4.964156e+01,4.203599e+01,1.940324e+01
std,5.766282e+00,1.443373e+02,2.771280e+02,1.413868e-01,4.337049e+01,1.083498e+02,3.811052e-01,2.274992e-01,3.221519e-01,7.920024e+01,...,7.637258e+00,1.947320e+01,8.876150e+00,1.276332e+01,1.318921e+01,2.937202e+00,2.341916e+00,1.751728e+01,1.187598e+01,8.885751e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,-4.985500e-03,3.308400e+03,3.557100e+03,6.695700e+00,2.534800e+01,3.967900e+01,2.420200e+03,...,7.348400e+00,-3.586600e-01,-5.222600e-03,-1.068800e-01,0.000000e+00,2.228800e+01,3.336900e+01,-6.834200e-01,-5.156500e-01,-6.774200e-03
25%,5.750000e+00,1.257500e+02,2.407500e+02,2.191700e-01,3.637600e+03,4.472900e+03,9.272700e+00,2.676300e+01,4.219000e+01,2.698300e+03,...,5.354500e+01,2.220600e+01,6.035700e+01,2.153300e+01,3.835700e+01,3.600000e+01,4.485600e+01,4.538500e+01,4.061600e+01,1.711400e+01
50%,1.050000e+01,2.505000e+02,4.805000e+02,2.504100e-01,3.664000e+03,4.509400e+03,9.356400e+00,2.690000e+01,4.235100e+01,2.705400e+03,...,5.398200e+01,2.505300e+01,6.149700e+01,2.213900e+01,3.992600e+01,3.811200e+01,4.631900e+01,4.804900e+01,4.119100e+01,1.826100e+01
75%,1.525000e+01,3.752500e+02,7.202500e+02,2.801300e-01,3.690800e+03,4.547200e+03,9.450600e+00,2.704000e+01,4.252600e+01,2.713800e+03,...,5.443300e+01,2.824100e+01,6.279000e+01,2.268700e+01,4.136500e+01,3.996100e+01,4.800800e+01,5.144600e+01,4.185300e+01,1.949000e+01
max,2.000000e+01,5.000000e+02,9.600000e+02,1.016800e+00,3.891700e+03,5.164300e+03,1.223600e+01,2.856500e+01,4.455000e+01,3.000500e+03,...,1.000000e+02,1.002100e+02,1.000200e+02,1.000900e+02,9.724500e+01,5.423000e+01,6.021600e+01,1.005800e+02,1.006100e+02,1.000100e+02

In [11]:
faulty_train['faulty_training'].describe()

,faultNumber,simulationRun,sample,xmeas_1,xmeas_2,xmeas_3,xmeas_4,xmeas_5,xmeas_6,xmeas_7,...,xmv_2,xmv_3,xmv_4,xmv_5,xmv_6,xmv_7,xmv_8,xmv_9,xmv_10,xmv_11
count,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,...,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06
mean,1.050000e+01,2.505000e+02,2.505000e+02,2.613588e-01,3.663777e+03,4.506046e+03,9.370345e+00,2.690156e+01,4.236419e+01,2.723005e+03,...,5.431755e+01,3.043177e+01,6.324830e+01,2.295485e+01,3.992297e+01,3.807265e+01,4.643742e+01,5.060598e+01,4.194845e+01,1.884376e+01
std,5.766282e+00,1.443373e+02,1.443373e+02,1.495384e-01,4.316941e+01,1.110368e+02,3.646151e-01,2.320034e-01,3.172128e-01,7.599384e+01,...,5.258092e+00,2.048365e+01,7.400080e+00,1.108258e+01,1.293348e+01,2.949138e+00,2.358468e+00,1.759840e+01,1.001227e+01,5.176705e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,-4.735000e-03,3.327400e+03,3.540700e+03,6.639900e+00,2.538600e+01,3.965600e+01,2.413800e+03,...,3.118400e+01,-2.718600e-01,-4.893100e-03,-9.941000e-02,0.000000e+00,2.280100e+01,3.492300e+01,-3.635500e-01,-2.809500e-01,-5.327000e-03
25%,5.750000e+00,1.257500e+02,1.257500e+02,2.183000e-01,3.636500e+03,4.469000e+03,9.264200e+00,2.676000e+01,4.218100e+01,2.697600e+03,...,5.349700e+01,2.228000e+01,6.031400e+01,2.142300e+01,3.831300e+01,3.604900e+01,4.487800e+01,4.547900e+01,4.057500e+01,1.714300e+01
50%,1.050000e+01,2.505000e+02,2.505000e+02,2.511300e-01,3.663300e+03,4.508500e+03,9.355200e+00,2.690100e+01,4.234800e+01,2.705600e+03,...,5.397000e+01,2.521500e+01,6.149900e+01,2.212900e+01,3.996700e+01,3.815000e+01,4.633900e+01,4.806500e+01,4.120600e+01,1.829500e+01
75%,1.525000e+01,3.752500e+02,3.752500e+02,2.832100e-01,3.690200e+03,4.548000e+03,9.456800e+00,2.704300e+01,4.252400e+01,2.715000e+03,...,5.444300e+01,2.879700e+01,6.284100e+01,2.273800e+01,4.150700e+01,3.999100e+01,4.803100e+01,5.188700e+01,4.194900e+01,1.953700e+01
max,2.000000e+01,5.000000e+02,5.000000e+02,1.017500e+00,3.906700e+03,5.175800e+03,1.224000e+01,2.848600e+01,4.465300e+01,3.000500e+03,...,1.000000e+02,1.001900e+02,1.000200e+02,1.001100e+02,9.752800e+01,5.312100e+01,5.998000e+01,1.005200e+02,1.003200e+02,1.000100e+02

In [12]:
fault_free_test_description = fault_free_test['fault_free_testing'].describe()
fault_free_train_description = fault_free_train['fault_free_training'].describe()
faulty_test_description = faulty_test['faulty_testing'].describe()
faulty_train_description = faulty_train['faulty_training'].describe()

In [13]:
fault_free_test_description.to_excel('fault_free_test_description.xlsx')
fault_free_train_description.to_excel('fault_free_train_description.xlsx')
faulty_test_description.to_excel('faulty_test_description.xlsx')
faulty_train_description.to_excel('faulty_train_description.xlsx')

In [14]:
df_free_train = fault_free_train['fault_free_training']
df_faulty_train = faulty_train['faulty_training']
df_free_test = fault_free_test['fault_free_testing']
df_faulty_test = faulty_test['faulty_testing']

In [15]:
train_data = pd.concat([df_free_train, df_faulty_train], axis=0, ignore_index=True)
test_data = pd.concat([df_free_test, df_faulty_test], axis=0, ignore_index=True)

In [16]:
rename_col = {
    'xmeas_1': 'a_feed_stream', 
    'xmeas_2': 'd_feed_stream', 
    'xmeas_3': 'e_feed_stream',
    'xmeas_4': 'a_and_c_feed_stream', 
    'xmeas_5': 'recycle_flow',
    'xmeas_6': 'reactor_feed_rate', 
    'xmeas_7': 'reactor_pressure', 
    'xmeas_8': 'reactor_level',
    'xmeas_9': 'reactor_temp', 
    'xmeas_10': 'purge_rate', 
    'xmeas_11': 'separator_temp',
    'xmeas_12': 'separator_level', 
    'xmeas_13': 'separator_pressure', 
    'xmeas_14': 'separator_underflow',
    'xmeas_15': 'stripper_level', 
    'xmeas_16': 'stripper_pressure', 
    'xmeas_17': 'stripper_underflow',
    'xmeas_18': 'stripper_temperature', 
    'xmeas_19': 'stripper_steam_flow', 
    'xmeas_20': 'compressor_work',
    'xmeas_21': 'reactor_cooling_water_outlet_temp', 
    'xmeas_22': 'condenser_cooling_water_outlet_temp',
    'xmeas_23': 'composition_of_a_rxtr_feed', 
    'xmeas_24': 'composition_of_b_rxtr_feed',
    'xmeas_25': 'composition_of_c_rxtr_feed', 
    'xmeas_26': 'composition_of_D_rxtr_feed',
    'xmeas_27': 'composition_of_e_rxtr_feed', 
    'xmeas_28': 'composition_of_f_rxtr_feed',
    'xmeas_29': 'composition_of_a_purge', 
    'xmeas_30': 'Composition_of_b_purge',
    'xmeas_31': 'composition_of_c_purge', 
    'xmeas_32': 'Composition_of_d_purge',
    'xmeas_33': 'composition_of_e_purge', 
    'xmeas_34': 'Composition_of_f_purge',
    'xmeas_35': 'composition_of_g_purge', 
    'xmeas_36': 'composition_of_h_purge',
    'xmeas_37': 'composition_of_d_product', 
    'xmeas_38': 'composition_of_e_product',
    'xmeas_39': 'composition_of_f_product', 
    'xmeas_40': 'composition_of_g_product',
    'xmeas_41': 'composition_of_h_product',
    'xmv_1': 'd_feed_flow_valve', 
    'xmv_2': 'e_feed_flow_valve', 
    'xmv_3': 'a_feed_flow_valve',
    'xmv_4': 'a_and_c_feed_flow_valve', 
    'xmv_5': 'compressor_recycle_valve',
    'xmv_6': 'purge_valve', 
    'xmv_7': 'separator_pot_liquid_flow_valve',
    'xmv_8': 'stripper_liquid_product_flow_valve', 
    'xmv_9': 'stripper_steam_valve',
    'xmv_10': 'reactor_cooling_water_flow_valve', 
    'xmv_11': 'condenser_cooling_water_flow_valve'
}

In [17]:
train_data.rename(columns=rename_col, inplace=True)
test_data.rename(columns=rename_col, inplace=True)

In [18]:
train_data['fault_label'] = (train_data['faultNumber'] != 0).astype(int)
test_data['fault_label'] = (test_data['faultNumber'] != 0).astype(int)

In [19]:
train_data['fault_label'].value_counts()

fault_label
1    5000000
0     250000
Name: count, dtype: int64

In [20]:
test_data['fault_label'].value_counts()

fault_label
1    9600000
0     480000
Name: count, dtype: int64

In [21]:
train_data.to_csv("train_data.txt", sep='\t', index=False)
test_data.to_csv("test_data.txt", sep='\t', index=False)